### ISSUE TITLE
[Bug] Foto verschijnt niet in Locaties in de buurt.

### ISSUE THREAD

**Issue by Fryslan** [chrissnoek/spotshare-frontend#3]
**Print screen:** https://i.imgur.com/mzEOkiJ.png
**Link:** https://app.spotshare.nl/dashboard
**Link van Locatie:** https://app.spotshare.nl/fotolocatie/oosterbierum
**Mogelijk probleem:** De foto is erg wijd, mogelijk kan hij niet goed gecropt worden voor icon.

**Comment by chrissnoek** [comment]
Volgens mij is deze nu ook opgelost, zou je eens kunnen checken?

**Comment by Fryslan** [comment]
> Volgens mij is deze nu ook opgelost, zou je eens kunnen checken?

Ik denk dat er een fout zit ergens, thumbnail is nu null.
Screenshot: https://i.imgur.com/heoCY9K.png

**Comment by chrissnoek** [comment]
Solved!

**Comment by Fryslan** [comment]
De oorspronkelijke bug bestaat nog steeds .
