### ISSUE TITLE
[Bug] Reactie op Artikel, Internal Server Error

### ISSUE THREAD

**Issue by Fryslan** [chrissnoek/spotshare-frontend#5]
**Print Screen:** https://i.imgur.com/Qmgmde5.png
**Link:** https://www.spotshare.nl/blog/beste-locaties-om-bollenvelden-te-fotograferen/
**Probleem:** Na het plaatsen van een reactie op een artikel uit de Blog sectie verscheen er een  Internal Server Error, het artikel geeft nu dezelfde error als ik hem open.

**Comment by chrissnoek** [comment]
Fixed!
